In [ ]:
"""

Name : Aman Jha
Lab : Deep Learning
Date : 25-03-2021
Title : Positive and Negative sentance classifier using random forest tree classifier

"""

'\n\nName : Aman Jha\nLab : Deep Learning\nDate : 25-03-2021\nTitle : Positive and Negative sentance classifier using random forest tree classifier\n\n'

In [ ]:
import numpy as np, re, nltk, pickle
from sklearn.datasets import load_files
nltk.download('stopwords')
from nltk.corpus import stopwords

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [ ]:
movie_data = load_files("/content/drive/MyDrive/Colab Notebooks/Classroom/positive and negative tweets")

X, y = movie_data.data, movie_data.target

# Text Pre-processing

In [ ]:
documents = []
from nltk.stem import WordNetLemmatizer
stemmer = WordNetLemmatizer()

In [ ]:
import nltk
nltk.download('wordnet')

[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


True

In [ ]:
for sen in range(0, len(X)) :

  document = re.sub(r'\W', ' ', str(X[sen]))

  document = re.sub(r'\s+[a-zA-Z]\s+', ' ', document)

  document = re.sub(r'\^[a-zA-Z]\s+', ' ', document)

  document = re.sub(r'\s+', ' ', document)

  document = re.sub(r'b\s+', '', document)

  document = document.lower()

  # Lemmatization
  document = document.split()

  document = [stemmer.lemmatize(word) for word in document]
  document = ' '.join(document)

  documents.append(document)

# Converting Text to Number

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer

vectorizer = CountVectorizer(max_features = 1500, min_df = 5, max_df = 0.7, stop_words = stopwords.words('english'))
X = vectorizer.fit_transform(documents).toarray()

In [ ]:
X[5]

array([0, 0, 0, ..., 0, 0, 0])

# Tf-IDf

In [ ]:
from sklearn.feature_extraction.text import TfidfTransformer

tfidfconverter = TfidfTransformer()

X = tfidfconverter.fit_transform(X).toarray()

In [ ]:
X[7]

array([0.        , 0.        , 0.        , ..., 0.        , 0.04499071,
       0.        ])

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidfconverter = TfidfVectorizer(max_features=1500, min_df=5, max_df=0.7, stop_words = stopwords.words('english'))
X = tfidfconverter.fit_transform(documents).toarray()

In [ ]:
X[5]

array([0., 0., 0., ..., 0., 0., 0.])

# Training and Testing Sets

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state=0)

In [ ]:
from sklearn.ensemble import RandomForestClassifier

classifier = RandomForestClassifier(n_estimators = 1000, random_state=0)
classifier.fit(X_train, y_train) # Using Random Forest Classifier

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=1000,
                       n_jobs=None, oob_score=False, random_state=0, verbose=0,
                       warm_start=False)

In [ ]:
y_pred = classifier.predict(X_test)

# Evaluating the Model

In [ ]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

print("Confusion Matrix:", confusion_matrix(y_test,y_pred))
print("Classification Report:", classification_report(y_test,y_pred))
print("Accuracy:", accuracy_score(y_test, y_pred))

Confusion Matrix: [[181  24]
 [ 50 147]]
Classification Report:               precision    recall  f1-score   support

           0       0.78      0.88      0.83       205
           1       0.86      0.75      0.80       197

    accuracy                           0.82       402
   macro avg       0.82      0.81      0.81       402
weighted avg       0.82      0.82      0.81       402

Accuracy: 0.8159203980099502


# Saving and Loading the Model

In [ ]:
%cd "/content/drive/MyDrive/Colab Notebooks/Classroom"

with open('text_classifier','wb') as picklefile :
  pickle.dump(classifier,picklefile)

/content/drive/MyDrive/Colab Notebooks/Classroom


In [ ]:
with open('text_classifier', 'rb') as training_model:
  model = pickle.load(training_model)

In [ ]:
y_pred2 = model.predict(X_test)

print(confusion_matrix(y_test, y_pred2))
print(classification_report(y_test, y_pred2))
print(accuracy_score(y_test, y_pred2))

[[181  24]
 [ 50 147]]
              precision    recall  f1-score   support

           0       0.78      0.88      0.83       205
           1       0.86      0.75      0.80       197

    accuracy                           0.82       402
   macro avg       0.82      0.81      0.81       402
weighted avg       0.82      0.82      0.81       402

0.8159203980099502
